#!/usr/bin/env node
/**
 * Detect hand edits to oagen-generated files in a PR diff.
 *
 * This is the single, language-agnostic detector shared by every WorkOS SDK
 * via the reusable `block-generated-edits` workflow. It must work across C#,
 * Kotlin, TypeScript, PHP, Python, Ruby, Go, Rust, Elixir, etc., so it keys
 * off the oagen marker *text* rather than any one language's comment syntax.
 *
 * A file is considered generated when one of its first `HEADER_SCAN_LINES`
 * lines contains the oagen marker (see `MARKER` below). Matching a substring
 * of the header — rather than the exact first line — means the comment prefix
 * (`//`, `#`, `<?php` preludes, `# frozen_string_literal:` banners, …) is
 * irrelevant and the marker is found wherever the generator places it.
 *
 * Generated files may contain hand-maintained regions fenced by
 * `@oagen-ignore-start` / `@oagen-ignore-end` comments; edits confined to
 * those regions are allowed. The fence check is also a substring match, so the
 * comment prefix on the fence lines doesn't matter. Fully hand-maintained
 * files carry `@oagen-ignore-file` instead of the generated marker, so they
 * never match and are ignored.
 *
 * Usage:
 *     check_generated_edits.ts <base_ref> <head_ref>
 *
 * Prints each offending file path (a generated file with changes outside its
 * fenced regions) on its own line to stdout, then exits 0. Anything that goes
 * wrong (bad refs, etc.) throws, so the workflow fails loudly rather than
 * silently letting an edit through.
 *
 * Pure git + Node built-ins: no third-party dependencies, and it runs under
 * Node's native TypeScript support (type stripping), so the workflow executes
 * it with a bare `node` — no install or build step.
 */

import { spawnSync } from "node:child_process";

// The marker text without any comment prefix, so it matches in every language.
const MARKER = "This file is auto-generated by oagen. Do not edit.";
const FENCE_START = "@oagen-ignore-start";
const FENCE_END = "@oagen-ignore-end";

// The marker is usually the first line, but some languages emit a preamble
// first (PHP's `<?php` + `declare(strict_types=1);`, Ruby's
// `# frozen_string_literal:` magic comment, license banners, …). Scan a small
// header window so the marker is found wherever it lands.
const HEADER_SCAN_LINES = 15;

const HUNK_RE = /^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/;

type Range = [number, number];

interface GitResult {
  status: number;
  stdout: string;
}

function git(...args: string[]): GitResult {
  const result = spawnSync("git", args, {
    encoding: "utf8",
    maxBuffer: 256 * 1024 * 1024,
  });
  if (result.error) {
    throw result.error;
  }
  return { status: result.status ?? 1, stdout: result.stdout ?? "" };
}

/** Split like Python's str.splitlines(): no trailing "" for a final newline. */
function splitLines(text: string): string[] {
  if (text === "") {
    return [];
  }
  return text.replace(/(\r\n|\r|\n)$/, "").split(/\r\n|\r|\n/);
}

/** Return the lines of `path` at `ref`, or null if it doesn't exist. */
function fileLines(ref: string, path: string): string[] | null {
  const result = git("show", `${ref}:${path}`);
  if (result.status !== 0) {
    return null;
  }
  return splitLines(result.stdout);
}

function isGenerated(lines: string[] | null): boolean {
  if (!lines || lines.length === 0) {
    return false;
  }
  return lines.slice(0, HEADER_SCAN_LINES).some((line) => line.includes(MARKER));
}

/**
 * Inclusive 1-based line ranges of hand-editable fenced regions.
 *
 * The fence marker lines themselves are included in the range, so editing a
 * fence comment counts as an allowed (fenced) change.
 */
function fenceRanges(lines: string[] | null): Range[] {
  if (!lines) {
    return [];
  }
  const ranges: Range[] = [];
  let start: number | null = null;
  for (let i = 0; i < lines.length; i++) {
    const lineno = i + 1;
    const line = lines[i];
    if (line.includes(FENCE_START)) {
      start = lineno;
    } else if (line.includes(FENCE_END) && start !== null) {
      ranges.push([start, lineno]);
      start = null;
    }
  }
  return ranges;
}

function inAnyRange(lineno: number, ranges: Range[]): boolean {
  return ranges.some(([start, end]) => start <= lineno && lineno <= end);
}

/**
 * True if the diff touches any line outside the fenced regions.
 *
 * Deleted lines are checked against the base file's fences (using their old
 * line numbers); added lines against the head file's fences (new line
 * numbers). A line-edit shows up as a delete + add, so a modification inside a
 * fence on both sides is correctly treated as fenced.
 */
function hasUnfencedChange(
  baseRef: string,
  headRef: string,
  path: string,
  baseFences: Range[],
  headFences: Range[],
): boolean {
  const diff = git(
    "diff",
    "--unified=0",
    "--no-renames",
    baseRef,
    headRef,
    "--",
    path,
  );
  if (diff.status !== 0) {
    // If we can't diff the file, fail safe by treating it as an offense.
    return true;
  }

  let oldLn = 0;
  let newLn = 0;
  for (const line of splitLines(diff.stdout)) {
    if (line.startsWith("@@")) {
      const match = HUNK_RE.exec(line);
      if (match) {
        oldLn = Number(match[1]);
        newLn = Number(match[3]);
      }
      continue;
    }
    if (line.startsWith("---") || line.startsWith("+++") || line.startsWith("\\")) {
      // File headers and "\ No newline at end of file" — not content.
      continue;
    }
    if (line.startsWith("-")) {
      if (!inAnyRange(oldLn, baseFences)) {
        return true;
      }
      oldLn += 1;
    } else if (line.startsWith("+")) {
      if (!inAnyRange(newLn, headFences)) {
        return true;
      }
      newLn += 1;
    }
  }
  return false;
}

function changedFiles(baseRef: string, headRef: string): string[] {
  const result = git("diff", "--name-only", "--no-renames", baseRef, headRef);
  if (result.status !== 0) {
    throw new Error(`git diff --name-only ${baseRef} ${headRef} failed`);
  }
  return splitLines(result.stdout).filter((line) => line !== "");
}

function findOffenders(baseRef: string, headRef: string): string[] {
  const offenders: string[] = [];
  for (const path of changedFiles(baseRef, headRef)) {
    const baseLines = fileLines(baseRef, path);
    const headLines = fileLines(headRef, path);

    // Generated on either side: catches edits, deletions (gone from head) and
    // newly added files masquerading as generated (absent from base).
    if (!isGenerated(baseLines) && !isGenerated(headLines)) {
      continue;
    }

    const baseFences = fenceRanges(baseLines);
    const headFences = fenceRanges(headLines);
    if (hasUnfencedChange(baseRef, headRef, path, baseFences, headFences)) {
      offenders.push(path);
    }
  }
  return offenders;
}

function main(argv: string[]): number {
  // argv mirrors Python's sys.argv: [scriptName, baseRef, headRef].
  if (argv.length !== 3) {
    process.stderr.write(`usage: ${argv[0]} <base_ref> <head_ref>\n`);
    return 2;
  }
  const [, baseRef, headRef] = argv;
  for (const path of findOffenders(baseRef, headRef)) {
    process.stdout.write(`${path}\n`);
  }
  return 0;
}

process.exit(main(process.argv.slice(1)));
