#!/usr/bin/env node
/**
 * End-to-end tests for the generated-file edit detector.
 *
 * Each scenario builds a throwaway git repo with a base commit and a head
 * commit, then runs the detector exactly as the reusable workflow does
 * (`node check_generated_edits.ts <base> <head>`) and asserts on the offender
 * paths it prints. Driving the real script through real `git diff` output is
 * the point: the bypasses this guards against live in how `--unified=0` diffs
 * render, so a unit test that stubbed the diff would test the wrong thing.
 *
 * Pure Node built-ins + git, run with a bare `node --test` (native type
 * stripping) — same toolchain the workflow uses, no install or build step.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT = join(
  dirname(fileURLToPath(import.meta.url)),
  "check_generated_edits.ts",
);

const MARKER = "// This file is auto-generated by oagen. Do not edit.";
const FENCE_START = "// @oagen-ignore-start";
const FENCE_END = "// @oagen-ignore-end";
const FILE = "generated.ts";

function git(cwd, ...args) {
  return execFileSync("git", args, { cwd, encoding: "utf8" });
}

/** Init a repo with a deterministic, self-contained identity (no global config). */
function makeRepo() {
  const dir = mkdtempSync(join(tmpdir(), "gen-edits-"));
  git(dir, "init", "-q", "-b", "main");
  git(dir, "config", "user.email", "test@example.com");
  git(dir, "config", "user.name", "Test");
  git(dir, "config", "commit.gpgsign", "false");
  return dir;
}

/** Write `lines` to `path` and commit; return the commit SHA. */
function commit(dir, path, lines, message) {
  writeFileSync(join(dir, path), lines.join("\n") + "\n");
  git(dir, "add", "-A");
  git(dir, "commit", "-q", "-m", message);
  return git(dir, "rev-parse", "HEAD").trim();
}

/** Commit `baseLines` then `headLines` for FILE; return the detector's offenders. */
function offendersFor(baseLines, headLines) {
  const dir = makeRepo();
  try {
    const base = commit(dir, FILE, baseLines, "base");
    const head = commit(dir, FILE, headLines, "head");
    const out = execFileSync("node", [SCRIPT, base, head], {
      cwd: dir,
      encoding: "utf8",
    });
    return out.split("\n").filter((line) => line !== "");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test("flags an insertion wrapped in self-minted fences", () => {
  const base = [MARKER, "const a = 1;"];
  const head = [MARKER, "const a = 1;", FENCE_START, "const evil = 2;", FENCE_END];
  assert.deepEqual(offendersFor(base, head), [FILE]);
});

test("flags fence markers smuggled via a `++`-prefixed content line", () => {
  // `++@oagen-ignore-start` renders as `+++@oagen-ignore-start` in the diff; a
  // prefix-based header test used to drop it while fenceRanges still honored it.
  const base = [MARKER, "const a = 1;"];
  const head = [
    MARKER,
    "const a = 1;",
    "++@oagen-ignore-start",
    "const evil = 2;",
    "++@oagen-ignore-end",
  ];
  assert.deepEqual(offendersFor(base, head), [FILE]);
});

test("flags an unfenced insertion (negative control)", () => {
  const base = [MARKER, "const a = 1;"];
  const head = [MARKER, "const a = 1;", "const evil = 2;"];
  assert.deepEqual(offendersFor(base, head), [FILE]);
});

test("flags removing a pre-existing fence marker (symmetric guard)", () => {
  const base = [MARKER, "const a = 1;", FENCE_START, "const hand = 1;", FENCE_END];
  const head = [MARKER, "const a = 1;", "const hand = 1;"];
  assert.deepEqual(offendersFor(base, head), [FILE]);
});

test("flags a `++`-prefixed content line added outside any fence", () => {
  const base = [MARKER, "const a = 1;"];
  const head = [MARKER, "const a = 1;", "++i"];
  assert.deepEqual(offendersFor(base, head), [FILE]);
});

test("allows a `++`-prefixed content line added inside a pre-existing fence", () => {
  const base = [MARKER, "const a = 1;", FENCE_START, "const hand = 1;", FENCE_END];
  const head = [MARKER, "const a = 1;", FENCE_START, "const hand = 1;", "++i", FENCE_END];
  assert.deepEqual(offendersFor(base, head), []);
});

test("allows a legit edit inside a pre-existing fence", () => {
  const base = [MARKER, "const a = 1;", FENCE_START, "const hand = 1;", FENCE_END];
  const head = [MARKER, "const a = 1;", FENCE_START, "const hand = 2;", FENCE_END];
  assert.deepEqual(offendersFor(base, head), []);
});

test("ignores a file with no oagen marker", () => {
  const base = ["const a = 1;"];
  const head = ["const a = 1;", "const b = 2;"];
  assert.deepEqual(offendersFor(base, head), []);
});
