/**
 * Tests for check_generated_edits.ts.
 *
 * Each test builds a throwaway git repository, commits a base and a head
 * state, and runs the real detector CLI against the two commits — the same
 * way the block-generated-edits workflow drives it. GIT_CONFIG_GLOBAL and
 * GIT_CONFIG_SYSTEM are pointed at /dev/null so the developer's own git
 * config (signing, quotePath, diff drivers) can't affect the outcome.
 *
 * Run with:
 *     node --test scripts/check_generated_edits.test.ts
 */

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { test } from "node:test";
import type { TestContext } from "node:test";
import { fileURLToPath } from "node:url";

const DETECTOR = join(
  dirname(fileURLToPath(import.meta.url)),
  "check_generated_edits.ts",
);

const MARKER = "This file is auto-generated by oagen. Do not edit.";
const GO_MARKER = "Code generated by oagen. DO NOT EDIT.";

// Base fixture: a generated file with one fenced region on lines 5-7.
const GENERATED = [
  `// ${MARKER}`,
  "export function add(a: number, b: number): number {",
  "  return a + b;",
  "}",
  "// @oagen-ignore-start",
  "export const custom = 1;",
  "// @oagen-ignore-end",
  "export const tail = 2;",
  "",
].join("\n");

const HERMETIC_ENV = {
  ...process.env,
  GIT_CONFIG_GLOBAL: "/dev/null",
  GIT_CONFIG_SYSTEM: "/dev/null",
};

interface Repo {
  dir: string;
  write(path: string, content: string | Buffer): void;
  remove(path: string): void;
  commit(message: string): string;
}

function makeRepo(t: TestContext): Repo {
  const dir = mkdtempSync(join(tmpdir(), "oagen-guard-test-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const git = (...args: string[]): string => {
    const result = spawnSync("git", args, {
      cwd: dir,
      encoding: "utf8",
      env: HERMETIC_ENV,
    });
    if (result.status !== 0) {
      throw new Error(`git ${args.join(" ")} failed: ${result.stderr}`);
    }
    return result.stdout;
  };
  git("init", "-q", "-b", "main");
  git("config", "user.email", "test@example.com");
  git("config", "user.name", "Test");
  return {
    dir,
    write(path, content) {
      writeFileSync(join(dir, path), content);
    },
    remove(path) {
      rmSync(join(dir, path));
    },
    commit(message) {
      git("add", "-A");
      git("commit", "-q", "-m", message);
      return git("rev-parse", "HEAD").trim();
    },
  };
}

function runDetector(repo: Repo, baseRef: string, headRef: string): string[] {
  const result = spawnSync(process.execPath, [DETECTOR, baseRef, headRef], {
    cwd: repo.dir,
    encoding: "utf8",
    env: HERMETIC_ENV,
  });
  assert.equal(result.status, 0, `detector failed: ${result.stderr}`);
  return result.stdout.split("\n").filter((line) => line !== "");
}

/** Commit `base` as gen.ts, then `head`, and return the detector's output. */
function offendersFor(
  t: TestContext,
  base: string | Buffer,
  head: string | Buffer | null,
): string[] {
  const repo = makeRepo(t);
  repo.write("gen.ts", base);
  const baseSha = repo.commit("base");
  if (head === null) {
    repo.remove("gen.ts");
  } else {
    repo.write("gen.ts", head);
  }
  const headSha = repo.commit("head");
  return runDetector(repo, baseSha, headSha);
}

test("flags a NUL-smuggled rewrite of a generated file (SEC-1586)", (t) => {
  // A NUL byte in the head blob makes git classify the diff as binary; the
  // guard must still see the rewrite as an unfenced change.
  const head = Buffer.from("// evil\u0000\nbackdoor();\n", "utf8");
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});

test("flags the same rewrite as plain text (negative control)", (t) => {
  assert.deepEqual(offendersFor(t, GENERATED, "// evil\nbackdoor();\n"), [
    "gen.ts",
  ]);
});

test("allows an edit inside a fenced region", (t) => {
  const head = GENERATED.replace(
    "export const custom = 1;",
    "export const custom = 42;",
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), []);
});

test("allows an insertion inside a fenced region", (t) => {
  const head = GENERATED.replace(
    "export const custom = 1;",
    "export const custom = 1;\nexport const custom2 = 2;",
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), []);
});

test("flags an edit outside the fenced region", (t) => {
  const head = GENERATED.replace(
    "export const tail = 2;",
    "export const tail = 3;",
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});

test("flags deletion of a generated file", (t) => {
  assert.deepEqual(offendersFor(t, GENERATED, null), ["gen.ts"]);
});

test("ignores non-generated files", (t) => {
  assert.deepEqual(offendersFor(t, "const a = 1;\n", "const a = 2;\n"), []);
});

test("recognizes the Go generated-file marker", (t) => {
  const base = `// ${GO_MARKER}\npackage sdk\n`;
  const head = `// ${GO_MARKER}\npackage sdk\n\nfunc Backdoor() {}\n`;
  assert.deepEqual(offendersFor(t, base, head), ["gen.ts"]);
});

test("flags an insertion wrapped in a newly minted fence", (t) => {
  // A PR author controls the head file, so a brand-new fence around a pure
  // insertion must not launder it as a hand-maintained change.
  const head = GENERATED.replace(
    "export const tail = 2;",
    [
      "// @oagen-ignore-start",
      "backdoor();",
      "// @oagen-ignore-end",
      "export const tail = 2;",
    ].join("\n"),
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});

test("flags a moved fence even when the fence count is unchanged", (t) => {
  // Delete the existing fence pair (deletions land inside the base fence
  // range) and mint a new pair around a payload elsewhere: the fence count
  // stays equal, so only the marker-line check catches it.
  const head = [
    `// ${MARKER}`,
    "export function add(a: number, b: number): number {",
    "  return a + b;",
    "}",
    "export const custom = 1;",
    "// @oagen-ignore-start",
    "backdoor();",
    "// @oagen-ignore-end",
    "export const tail = 2;",
    "",
  ].join("\n");
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});

test("flags hand edits to a fence marker line", (t) => {
  const head = GENERATED.replace(
    "// @oagen-ignore-end",
    "// @oagen-ignore-end (widened)",
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});

test("flags a new file masquerading as generated, even fully fenced", (t) => {
  const repo = makeRepo(t);
  repo.write("README.md", "# sdk\n");
  const baseSha = repo.commit("base");
  repo.write(
    "gen.ts",
    [
      "// @oagen-ignore-start",
      `// ${MARKER}`,
      "backdoor();",
      "// @oagen-ignore-end",
      "",
    ].join("\n"),
  );
  const headSha = repo.commit("head");
  assert.deepEqual(runDetector(repo, baseSha, headSha), ["gen.ts"]);
});

test("flags edits to generated files at non-ASCII paths", (t) => {
  // With core.quotePath (the default) git C-quotes this path in --name-only
  // output; without -z the quoted form fails the `git show` lookups and the
  // file is silently skipped.
  const repo = makeRepo(t);
  repo.write("généré.ts", GENERATED);
  const baseSha = repo.commit("base");
  repo.write(
    "généré.ts",
    GENERATED.replace("export const tail = 2;", "export const tail = 3;"),
  );
  const headSha = repo.commit("head");
  assert.deepEqual(runDetector(repo, baseSha, headSha), ["généré.ts"]);
});

test("flags added content lines that start with ++", (t) => {
  // "+ ++counter;" renders as "+++counter;" in the diff; a bare prefix check
  // would skip it as a "+++ b/path" file header and never fence-check it.
  const head = GENERATED.replace(
    "export const tail = 2;",
    "export const tail = 2;\n++counter;",
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});

test("flags a CR-smuggled fake hunk header", (t) => {
  // A lone \r is not a line terminator for git. If the parser split on \r,
  // the tail of this fence-end line would parse as an "@@" hunk header,
  // repositioning the following insertion inside the fence range while it
  // actually lands outside the fence in the head file.
  const head = GENERATED.replace(
    "// @oagen-ignore-end",
    "// @oagen-ignore-end\r@@ -0,0 +6,0 @@\nbackdoor();",
  );
  assert.deepEqual(offendersFor(t, GENERATED, head), ["gen.ts"]);
});
